# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
