# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_session_from_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='stype',
            field=models.CharField(choices=[('keynote', 'Keynote'), ('lightning', 'Lightning Talk (5 Minutes)'), ('talk-short', 'Short Talk (20 Minutes)'), ('talk-long', 'Talk (50 Minutes)'), ('tutorial', 'Tutorial (3 Hours)'), ('non-talk', 'Non Talk')], max_length=25, verbose_name='Session Type'),
        ),
    ]
