# Generated by Django 2.0.10 on 2019-03-15 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190310_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('ticket_id', models.CharField(max_length=255, unique=True)),
                ('prize', models.CharField(blank=True, max_length=255, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Conference')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='stype',
            field=models.CharField(choices=[('keynote', 'Keynote'), ('lightning', 'Lightning Talk'), ('talk-short', 'Short Talk'), ('talk-long', 'Talk'), ('tutorial', 'Tutorial'), ('non-talk', 'Non Talk')], max_length=25, verbose_name='Session Type'),
        ),
    ]
