# Generated by Django 2.0.10 on 2019-03-31 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0007_auto_20190315_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
