# Generated by Django 2.0.9 on 2019-04-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_session_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(max_length=255)),
                ('redirect_to', models.CharField(max_length=255)),
            ],
        ),
    ]
