# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialhandle',
            name='site',
            field=models.CharField(choices=[('about.me', 'About.Me'), ('facebook', 'Facebook'), ('github', 'Github'), ('gplus', 'Google+'), ('twitter', 'Twitter'), ('web', 'Web')], max_length=25),
        ),
        migrations.AlterField(
            model_name='socialhandle',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
