# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171028_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_import',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
