# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_from_import'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialhandle',
            name='site',
            field=models.CharField(choices=[('about.me', 'About.Me'), ('facebook', 'Facebook'), ('github', 'Github'), ('gplus', 'Google+'), ('twitter', 'Twitter')], max_length=25),
        ),
    ]
