# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171028_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialhandle',
            name='site',
            field=models.CharField(choices=[('about.me', 'About.Me'), ('facebook', 'Facebook'), ('github', 'Github'), ('gplus', 'Google+'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=25),
        ),
    ]
