# Generated by Django 2.0.6 on 2018-06-24 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171030_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialhandle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_handles', to=settings.AUTH_USER_MODEL),
        ),
    ]
