# Generated by Django 2.0.10 on 2019-03-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_user_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reviewer',
        ),
    ]
